### ISSUE TITLE
JOSS review

### ISSUE THREAD

**Issue by ziyiyin97** [baxmittens/OpenGeoSysUncertaintyQuantification.jl#3]
https://github.com/openjournals/joss-reviews/issues/6725

Apart from comments from the other reviewer, I have the following comments about the manuscript itself:

1. The first paragraph in the statement of need can benefit from a reference.
2. Line 26-29 is a bit confusing. Probably can rephrase to "This package was designed with the aim to be explicitly related to the OGS6 project. However, care was taken to ensure that the underlying packages could potentially be still applicable to other projects."
3. Line 38: it would be good if authors can briefly indicate their contribution on top of other relevant Julia packages.

I will post more comments for the software in a bit ...

**Comment by baxmittens** [comment]
Hello @ziyiyin97 

thank you for your comments.
I gladly adopted your improvement suggestion from your first two points.

Regarding 3: I think since all of them are repositories which I own, it is comprehensible that I am the main or even only contributor to all this projects. For 2 of them there is a reference for a JOSS paper given with my name to it. Should be ok, I think or am I wrong?

**Comment by ziyiyin97** [comment]
In terms of the software and documentation, I am not sure how to run the examples in this section https://baxmittens.github.io/OpenGeoSysUncertaintyQuantification.jl/dev/#Usage. The path does not exist. It seems that this example is outdated (probably due to the changes requested by the other reviewer). Please fix. Thanks!

**Comment by baxmittens** [comment]
@ziyiyin97 
You're right. I altered the documentation.
You can update to OpenGeoSysUncertaintyQuantification@0.1.5 and the example and the test should work. Hope this fixes your issues. Otherwise, please write again here.
Thank you.

**Comment by ziyiyin97** [comment]
Thanks! Things run fine now. I think this change is necessary https://github.com/baxmittens/OpenGeoSysUncertaintyQuantification.jl/pull/4

Also it would be good to mention to the users that running this complete example might take a long while (i.e. it is not a "minimal" example that one expects to finish running in a few seconds). Also would be good to mention if the users need a reasonable machine to run this example (i.e. can users run this example on a small laptop given memory or other constraints?)

**Comment by baxmittens** [comment]
Hello @ziyiyin97 
I merged your pull request. Thank you for that catch.
In the next release, the test will only generate the bare minimum of sample points.
![image](https://github.com/baxmittens/OpenGeoSysUncertaintyQuantification.jl/assets/100423479/87506e5e-a479-4ca2-8e44-37e5de404e23)
For me the tests runs in under one minute which is fine, is guess. Right?

Greetz max

**Comment by ziyiyin97** [comment]
I finished the checklist. Congrats! I will close this issue now.
